# Generated by Django 4.2.6 on 2023-11-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('idEntreprise', models.AutoField(primary_key=True, serialize=False)),
                ('cote', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('idjoueur', models.AutoField(primary_key=True, serialize=False)),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEntreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_game.entreprise')),
                ('idjoueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_game.joueur')),
            ],
        ),
    ]
