# Generated by Django 4.2.7 on 2023-12-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_game', '0004_rename_identreprise_placement_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='event',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
    ]
